// The local env file of the evidence stack (`packages/evidence/.env`, untracked). Since the single
// compose.yaml of the homelab, the secrets normally arrive as environment variables from the root `.env`;
// this file is the fallback for a machine that still runs the tools by hand: `ensureEnvFile` creates it
// with random values so nothing secret is ever committed, and appends a key added later.
// `.env.example` documents the names.

import { randomBytes } from 'node:crypto';
import { existsSync } from 'node:fs';
import { appendFile, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

export const ENV_FILE = fileURLToPath(new URL('../.env', import.meta.url));

type Random = (bytes: number) => string;
const hexRandom: Random = (n) => randomBytes(n).toString('hex');

/** Every secret of the stack, in file order; web passwords use the local development default. */
const SECRETS: ReadonlyArray<readonly [key: string, value: number | 'admin']> = [
  ['PHOENIX_SECRET', 32],
  ['PHOENIX_SYSTEM_KEY', 32],
  ['PHOENIX_ADMIN_PASSWORD', 'admin'],
  ['METABASE_ADMIN_PASSWORD', 'admin'],
];

const secretValue = (value: number | 'admin', random: Random): string => (typeof value === 'number' ? random(value) : value);

/** A fresh env file: two random service secrets and simple web passwords. */
export function renderEnvFile(random: Random = hexRandom): string {
  return [
    '# Local secrets of the evidence stack, generated by packages/evidence/src/env-file.ts.',
    '# Never committed. Phoenix (http://127.0.0.1:6006) admin sign-in: admin@localhost with PHOENIX_ADMIN_PASSWORD.',
    '# Metabase (http://127.0.0.1:3300) sign-in: admin@demiurgo.local with METABASE_ADMIN_PASSWORD.',
    ...SECRETS.map(([key, value]) => `${key}=${secretValue(value, random)}`),
    '',
  ].join('\n');
}

/**
 * The `KEY=value` pairs of an env file (the subset compose reads: one pair per line, `#` comments and
 * blank lines ignored, optional single or double quotes around the value, no interpolation).
 */
export function parseEnvFile(text: string): Record<string, string> {
  const pairs: Record<string, string> = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (line === '' || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    const quote = value[0];
    if ((quote === '"' || quote === "'") && value.length >= 2 && value.endsWith(quote)) value = value.slice(1, -1);
    pairs[key] = value;
  }
  return pairs;
}

/** The lines that a file written by an earlier version lacks. */
export function missingSecretLines(existing: Record<string, string>, random: Random = hexRandom): string[] {
  return SECRETS.filter(([key]) => existing[key] === undefined).map(([key, value]) => `${key}=${secretValue(value, random)}`);
}

export type EnvFileState = { state: 'created' } | { state: 'extended'; keys: string[] } | { state: 'unchanged' };

/** Creates the env file when it is missing and appends the secrets an existing one lacks. */
export async function ensureEnvFile(path = ENV_FILE): Promise<EnvFileState> {
  if (!existsSync(path)) {
    await writeFile(path, renderEnvFile(), { encoding: 'utf8', flag: 'wx' });
    return { state: 'created' };
  }
  const text = await readFile(path, 'utf8');
  const lines = missingSecretLines(parseEnvFile(text));
  if (lines.length === 0) return { state: 'unchanged' };
  const separator = text === '' || text.endsWith('\n') ? '' : '\n';
  await appendFile(path, `${separator}${lines.join('\n')}\n`, 'utf8');
  return { state: 'extended', keys: lines.map((l) => l.slice(0, l.indexOf('='))) };
}
