// `pnpm evidence:up` and `pnpm evidence:down`: the evidence stack (compose.evidence.yaml) with its
// local secrets. Phoenix runs with authentication on, so the compose needs a JWT secret, an admin
// secret (the collector's bearer token) and the first admin password; Metabase needs the password of
// its admin account (`pnpm evidence metabase-setup` creates it). They live in
// `packages/evidence/.env`, untracked (`.env` is git-ignored) and generated here on the first `up`
// with random values, so nothing secret is ever committed. A key added later (METABASE_ADMIN_PASSWORD
// came with phase 5) is appended to an existing file. `.env.example` documents the names.

import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync } from 'node:fs';
import { appendFile, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

export const ENV_FILE = fileURLToPath(new URL('../.env', import.meta.url));
const COMPOSE_FILE = fileURLToPath(new URL('../../../compose.evidence.yaml', import.meta.url));

type Random = (bytes: number) => string;
const hexRandom: Random = (n) => randomBytes(n).toString('hex');

/** Every secret of the stack, in file order, with how many random bytes each one takes. */
const SECRETS: ReadonlyArray<readonly [key: string, bytes: number]> = [
  ['PHOENIX_SECRET', 32],
  ['PHOENIX_SYSTEM_KEY', 32],
  ['PHOENIX_ADMIN_PASSWORD', 12],
  ['METABASE_ADMIN_PASSWORD', 12],
];

/** The `.env` of a fresh install: four random secrets, only ever read on this machine. */
export function renderEnvFile(random: Random = hexRandom): string {
  return [
    '# Local secrets of the evidence stack, generated by `pnpm evidence:up` (packages/evidence/src/up.ts).',
    '# Never committed. Phoenix (http://127.0.0.1:6006) admin sign-in: admin@localhost with PHOENIX_ADMIN_PASSWORD.',
    '# Metabase (http://127.0.0.1:3300) sign-in: evidence@demiurgo.local with METABASE_ADMIN_PASSWORD.',
    ...SECRETS.map(([key, bytes]) => `${key}=${random(bytes)}`),
    '',
  ].join('\n');
}

/**
 * The `KEY=value` pairs of an env file (the subset compose reads: one pair per line, `#` comments and
 * blank lines ignored, optional single or double quotes around the value, no interpolation).
 */
export function parseEnvFile(text: string): Record<string, string> {
  const pairs: Record<string, string> = {};
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (line === '' || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    const quote = value[0];
    if ((quote === '"' || quote === "'") && value.length >= 2 && value.endsWith(quote)) value = value.slice(1, -1);
    pairs[key] = value;
  }
  return pairs;
}

/** The lines that a file written by an earlier version lacks: one `KEY=random` per missing secret. */
export function missingSecretLines(existing: Record<string, string>, random: Random = hexRandom): string[] {
  return SECRETS.filter(([key]) => existing[key] === undefined).map(([key, bytes]) => `${key}=${random(bytes)}`);
}

export type EnvFileState = { state: 'created' } | { state: 'extended'; keys: string[] } | { state: 'unchanged' };

/** Creates the env file when it is missing and appends the secrets an existing one lacks. */
export async function ensureEnvFile(path = ENV_FILE): Promise<EnvFileState> {
  if (!existsSync(path)) {
    await writeFile(path, renderEnvFile(), { encoding: 'utf8', flag: 'wx' });
    return { state: 'created' };
  }
  const text = await readFile(path, 'utf8');
  const lines = missingSecretLines(parseEnvFile(text));
  if (lines.length === 0) return { state: 'unchanged' };
  const separator = text === '' || text.endsWith('\n') ? '' : '\n';
  await appendFile(path, `${separator}${lines.join('\n')}\n`, 'utf8');
  return { state: 'extended', keys: lines.map((l) => l.slice(0, l.indexOf('='))) };
}

function compose(args: string[]): number {
  const result = spawnSync('docker', ['compose', '--env-file', ENV_FILE, '-f', COMPOSE_FILE, ...args], { stdio: 'inherit' });
  return result.status ?? 1;
}

async function main(argv: string[]): Promise<number> {
  const action = argv[0] ?? 'up';
  if (action !== 'up' && action !== 'down') {
    console.error('Usage: node packages/evidence/src/up.ts [up|down]');
    return 2;
  }
  const env = await ensureEnvFile();
  if (env.state === 'created') console.log(`Created ${ENV_FILE} with new local secrets.`);
  else if (env.state === 'extended') console.log(`Added ${env.keys.join(', ')} to ${ENV_FILE}.`);
  return compose(action === 'up' ? ['up', '-d', '--wait'] : ['down']);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  process.exitCode = await main(process.argv.slice(2));
}
