// `pnpm evidence:up` and `pnpm evidence:down`: the evidence stack (compose.evidence.yaml) with its
// local secrets. Phoenix runs with authentication on, so the compose needs a JWT secret, an admin
// secret (the collector's bearer token) and the first admin password. They live in
// `packages/evidence/.env`, untracked (`.env` is git-ignored) and generated here on the first `up`
// with random values, so nothing secret is ever committed. `.env.example` documents the names.

import { spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { existsSync } from 'node:fs';
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

export const ENV_FILE = fileURLToPath(new URL('../.env', import.meta.url));
const COMPOSE_FILE = fileURLToPath(new URL('../../../compose.evidence.yaml', import.meta.url));

/** The `.env` of a fresh install: three random secrets, only ever read by compose on this machine. */
export function renderEnvFile(random: (bytes: number) => string = (n) => randomBytes(n).toString('hex')): string {
  return [
    '# Local secrets of the evidence stack, generated by `pnpm evidence:up` (packages/evidence/src/up.ts).',
    '# Never committed. Phoenix (http://127.0.0.1:6006) admin sign-in: admin@localhost with PHOENIX_ADMIN_PASSWORD.',
    `PHOENIX_SECRET=${random(32)}`,
    `PHOENIX_SYSTEM_KEY=${random(32)}`,
    `PHOENIX_ADMIN_PASSWORD=${random(12)}`,
    '',
  ].join('\n');
}

/** Creates the env file when it is missing; true when it was created now. */
export async function ensureEnvFile(path = ENV_FILE): Promise<boolean> {
  if (existsSync(path)) return false;
  await writeFile(path, renderEnvFile(), { encoding: 'utf8', flag: 'wx' });
  return true;
}

function compose(args: string[]): number {
  const result = spawnSync('docker', ['compose', '--env-file', ENV_FILE, '-f', COMPOSE_FILE, ...args], { stdio: 'inherit' });
  return result.status ?? 1;
}

async function main(argv: string[]): Promise<number> {
  const action = argv[0] ?? 'up';
  if (action !== 'up' && action !== 'down') {
    console.error('Usage: node packages/evidence/src/up.ts [up|down]');
    return 2;
  }
  if (await ensureEnvFile()) console.log(`Created ${ENV_FILE} with new local secrets.`);
  return compose(action === 'up' ? ['up', '-d', '--wait'] : ['down']);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  process.exitCode = await main(process.argv.slice(2));
}
