// Genera el módulo de tablas del dominio desde `design/datos/`. La deriva (tablas en el
// dominio distintas de las de design/) hace fallar `pnpm gate:deriva`.

import { capabilitiesSchema, transitionsSchema, tableInconsistencies } from '@demiurgo/domain/tables/schemas';
import { parse as parseYaml } from 'yaml';

export const TABLES_MODULE_PATH = 'packages/domain/src/generated/tables.ts';

export function generateTablesModule(capabilitiesYaml: string, transitionsYaml: string): string {
  const cap = capabilitiesSchema.parse(parseYaml(capabilitiesYaml));
  const trans = transitionsSchema.parse(parseYaml(transitionsYaml));
  const errors = tableInconsistencies(cap, trans);
  if (errors.length > 0) throw new Error(`Tablas incoherentes:\n- ${errors.join('\n- ')}`);
  return [
    '// Generated by `node packages/design/src/cli.ts derive` from design/data/. Do not edit by hand.',
    '',
    `export const CAPABILITIES = ${JSON.stringify(cap, null, 2)} as const;`,
    '',
    `export const TRANSITIONS = ${JSON.stringify(trans, null, 2)} as const;`,
    '',
  ].join('\n');
}
